### ISSUE TITLE
MicroLogix/SLC500 support?

### ISSUE THREAD

**Issue by thatcadguy** [kyle-github/libplctag#1]
Hi, this is a question rather than an issue, but does this library support SLC500 PLCs like the MicroLogix series? I actually just got done forking and fixing TuxEIP for our own purposes and then found your library which might work better for us. Thanks.

P.S. I might be able to test on a CompactLogix (as well as the MicroLogix), if you are still needing testing. I might be able to help out with coding too.

**Comment by kyle-github** [comment]
Can I close this?  Did it work?

**Comment by thatcadguy** [comment]
Don't remember if I tested or not, but yes it can be closed

**Comment by kyle-github** [comment]
OK, thanks!
