### ISSUE TITLE
String support

### ISSUE THREAD

**Issue by reyanvaldes** [kyle-github/libplctag#11]
Kyle, 
It would be great to have capability of reading/writing string tags in the library to be more completed. In some applications the strings manners and it is so important as numeric data. Maybe when Get String we can have as parameters: offset, and max. length, and type of string (null terminating, leading length), to allow read/write string at least for most recently AB PLCs.

Thank you a lot for very nice work and sharing with community

**Comment by kyle-github** [comment]
Hi Reyan,

I've been travelling at at conferences for most of the last two months. I will get to your request in a bit.  Please be patient while I catch up.  Thanks!

Best,
Kyle

**Comment by reyanvaldes** [comment]
Hi Kyle
I hope you had good experience.

Thanks
Reyan

**Comment by kyle-github** [comment]
I have opened a new mailing list in Google groups: libplctag.  Please bring this discussion there.  I would like to get a wider audience.  Thanks!

**Comment by kyle-github** [comment]
Here is the new Google forum:

[libplctag](https://groups.google.com/forum/#!forum/libplctag)

I want to have the discussion there.  Please sign up!
