### ISSUE TITLE
Dll x86

### ISSUE THREAD

**Issue by franklupo** [kyle-github/libplctag#138]
Hi,
Are possible to make dll x86 for windows and linux?

Best regards.

**Comment by kyle-github** [comment]
Hi @franklupo, 

I have been looking and I do not see a way to make Azure Pipelines spin up a 32-bit VM.   I will keep looking.   Perhaps GitHub has something.

I have no personal VMs with 32-bit Windows. I do have a VM with 32-bit Debian 10 x86.   I will see if it is easy to set that up.

**Comment by kyle-github** [comment]
It does not appear that I can get a VM with 32-bit Windows easily in the free tier of Azure Pipelines.   I do have a 32-bit Debian VM on my laptop and I used that to create a 32-bit Debian 10 release.  I added that to the pre-release 2.0.34.  Please try it and let me know if it works for you!

**Comment by franklupo** [comment]
Thank

**Comment by kyle-github** [comment]
Hmm, I wonder if it is possible to build a 32-bit DLL on 64-bit Windows?   I will see if I can figure this out.   It might also be possible for Linux.  That would allow me to build all these DLLs from Azure.

**Comment by franklupo** [comment]
Hi,
I think it is possible to create both in one solution.

Bets regards

**Comment by kyle-github** [comment]
It was not as easy as I had hoped, but I was able to create 32-bit DLLs for Windows and Linux.  Unfortunately, I cannot test the Windows DLLs as I have no 32-bit Windows systems.  Can you please check the latest pre-release for v2.0.35 and see if the 32-bit Windows binaries work?  Thanks!

I have this fully integrated into the CI system so every time the master branch is pushed, Azure Pipelines will build all five sets of binaries.

I see that you are in Italy.  You have all our best wishes at this horrible time.  Stay safe!

**Comment by franklupo** [comment]
ANDRÀ TUTTO BENE

Grazie

**Comment by kyle-github** [comment]
I hope it will all be OK!

Please reopen this if the DLLs are not working!   Thanks for bringing this up.
