### ISSUE TITLE
Building the Library

### ISSUE THREAD

**Issue by QuinDennis** [kyle-github/libplctag#40]
Is there a guide perhaps on getting this set up and compiled?  Like, Building a simple user program?

<code>
#include <stdio.h>
#include <unistd.h>
//#include <../lib/libplctag.h>
#include "libplctag.h"
//#include "utils.h"
...
cc -o test test.c
...
 cc -o readTag readTag.c
/tmp/ccKd8UdD.o: In function `main':
readTag.c:(.text+0x1d): undefined reference to `plc_tag_create'
readTag.c:(.text+0x32): undefined reference to `plc_tag_read'
readTag.c:(.text+0x7f): undefined reference to `plc_tag_get_int32'
readTag.c:(.text+0xb3): undefined reference to `plc_tag_destroy'
collect2: error: ld returned 1 exit status

**Comment by kyle-github** [comment]
There is a build instruction file called BUILD.md that outlines how to build.  Making the project also builds all the examples in the src/examples directory.  You can find many small programs there covering different uses of the library.  In addition there are some contributed wrappers for C++, Python and a semi-supported wrapper for Java.
