### ISSUE TITLE
Add accessory/helper function to get tag list from Logix PLCs

### ISSUE THREAD

**Issue by ghost** [kyle-github/libplctag#46]
Kyle, been checking out pylogix lately (https://github.com/dmroeder/pylogix), a small Python library for dealing with Logix PLCs. That library includes a function aptly named GetTagList(). In future this would be very helpful to add to the library, I think. When I have some more free time I might be able to port the Python code from that project to C and submit a PR. It's Apache licensed so we would just give attribution and link or something.

**Comment by kyle-github** [comment]
Interesting!  I had looked at cpppo too (also Python).

I will queue this for a feature drop.   I will be out of the country for a couple of weeks on business, so I won't be able to look at this until mid to late February.

This might be a good test of some new internal architecture changes I want to try.

**Comment by kyle-github** [comment]
This is in progress.

Thanks to a new user, I got more documentation on how this is supposed to work.  AB did publish some docs on this publicly.

**Comment by afiya-g** [comment]
Hello Kyle,

Does current version supports now browsing of AB controller tags?
I'm using libplctag lib for my client project, and the requirement is to browse the AB controller tags.
If the current version is supporting, can you please let know how to do it.

Regards,
Syed.

**Comment by vlcvboyer** [comment]
Hi Kyle,
Do you need some help on this feature Implementation ?

**Comment by kyle-github** [comment]
I have some old code that does not work with the current state of the library.    

I should really dust that off and port it to the current version.  This feature is requested often!

If you want to take a swing at it, I would love the help!

**Comment by kyle-github** [comment]
I have some old code that does not work with the current state of the library.    

I should really dust that off and port it to the current version.  This feature is requested often!

If you want to take a swing at it, I would love the help!

**Comment by kyle-github** [comment]
The way I prototyped this was to have a special tag name, "@tags".

There is some very annoying logic you need to implement with the internal tag IDs.

**Comment by vlcvboyer** [comment]
can please indicate which branch contains this preliminary code?
Thanks

**Comment by kyle-github** [comment]
This has been reopened as ticket #97.

**Comment by kyle-github** [comment]
Hi @vlcvboyer, there is an almost working version in the branch "tag_list" on GitHub.   I ran out of time today to get more done.

**Comment by kyle-github** [comment]
This has been implemented in version 2.0.17.

**Comment by vlcvboyer** [comment]
Thks !
I'll test it in a short time.
