### ISSUE TITLE
Adding plctag.dll into c# projects

### ISSUE THREAD

**Issue by rishidamco** [kyle-github/libplctag#57]
Hi There,

I have follow all the steps and created the plctag.dll and it is working as well when calling using provided exe programs like tag_rw.exe etc.

I wanted to include functionality in my c# project and make direct calls to plctag.dll instead of using provided exe programs.

Is there a way, I can add this in my c# programs and call it from there.

Please advise.

Rishi

**Comment by kyle-github** [comment]
A user has created a set of wrappers for C# here:

https://github.com/mesta1/libplctag-csharp
