### ISSUE TITLE
error in debug message output

### ISSUE THREAD

**Issue by kyranf** [kyle-github/libplctag#59]
https://github.com/kyle-github/libplctag/blob/8365763e654a9bb44248a16d7de8b07faa466894/src/examples/simple_cpp.cpp#L71

This line should say that it could not write the tag, not read it, right? Copy-paste error basically.

**Comment by kyle-github** [comment]
Hmm, looks like it.   Adding to the list.  Sigh.

**Comment by kyle-github** [comment]
Fixed, only a year late (!!!), in version 1.5.12.
