### ISSUE TITLE
Support automatic reconnection

### ISSUE THREAD

**Issue by kyle-github** [kyle-github/libplctag#65]
It is too annoying to have to do simple reconnections in every app using the library.   And, the rules for when reconnection works are not as easy to understand as they should be.

Implement reconnection within the library.   TBD on how this should look.

**Comment by xinthose** [comment]
An auto-reconnect feature would be great, like setting the reconnect option to MySQL.

**Comment by kyle-github** [comment]
Some of this is working in 2.0 so far, but I still need a way to pass along the reconnection timeout time.  There are multiple aspects to this:

- how long should the library wait before giving up?  It cannot be a fixed value as connections vary widely in the amount of time, and variance, it takes to get a response.
- once we decide to terminate a session, how long should we wait until trying it again?
- how many times should we retry.  Alternatively, how long should we go without a successful reconnection?

**Comment by kyle-github** [comment]
A version of this is in 2.0.  I will open additional bugs against the library for specific changes.
