### ISSUE TITLE
Cannot link with mySQL

### ISSUE THREAD

**Issue by truong32ct** [kyle-github/libplctag#67]
Hi Kyle,
I am trying to read data from PLC into my raspberry pi and then push the data into mySQL. I execute the reading section and it is ok but when I include some mySQL libraries and compile, it cannot create a execution file with the fault I capture. The createdb.c is in libplctag/src/example. 
The command line I used was: gcc -o createdb createdb.c utils_posix.c -L . -lplctag -lpthread -I .. -I .-std=c99  `mysql_config --cflags --libs`
![image](https://user-images.githubusercontent.com/14815789/38907825-c1f7c652-42e7-11e8-8aa2-293221b43df6.png)
I hope that you can help me out.

**Comment by kyle-github** [comment]
I suggest trying to make some small examples with just MySQL.   There are many examples of code online.   Usually people use other languages than C to interface with MySQL but the client libraries can be used from C.
