### ISSUE TITLE
plc_tag_set_float32 will always return PLCTAG_STATUS_OK

### ISSUE THREAD

**Issue by vollmant** [kyle-github/libplctag#71]
It looks like the return value is incorrect for **plc_tag_set_float32** on line #1459 in [/src/lib/libplctag_tag.c](https://github.com/kyle-github/libplctag/blob/master/src/lib/libplctag_tag.c#L1459) 

Currently it is
``` return PLCTAG_STATUS_OK; ```
Should be 
``` return rc; ```

**Comment by kyle-github** [comment]
Fixed in 1.5.10.  Thanks again!

**Comment by vollmant** [comment]
no problem. Thanks for the quick response!
