### ISSUE TITLE
String conection in example don't work

### ISSUE THREAD

**Issue by garciaolais** [kyle-github/libplctag#84]
Hi

I copied the sample code from README section but when I ran it i got an error.

**Error setting up tag internal state. Error PLCTAG_ERR_NOT_IMPLEMENTED**

I changed elem_type=DINT for elem_size=4 in and works fine. 

PLC : CompactLogix 5323e
OS: Windows 10 , WSL ubuntu 18.04
libplctag 2.0

**Comment by kyle-github** [comment]
Hi,

Thanks for the bug report!   I fixed the README file.  That was apparently copied only partially in the README!

This is fixed in the 2.0.5 version.
