### ISSUE TITLE
Is there the plctag.dll compiled in x64?

### ISSUE THREAD

**Issue by cecaceo** [kyle-github/libplctag#89]
I'm making a program that uses some libraries that works in x64, but "plctag.dll" works in x86. Is there a version of "plctag.dll" working in x64?

**Comment by kyle-github** [comment]
Were you able to build the library?

**Comment by cecaceo** [comment]
Dear Kyle,
Yes, I found the source code of the "plctag.dll" and I was able to rebuild
it in x64.

Best regards
Alex

Il giorno mar 5 feb 2019 alle ore 04:10 Kyle Hayes <notifications@github.com>
ha scritto:
