### ISSUE TITLE
Max elem_count for elem_size = 2 (INT)

### ISSUE THREAD

**Issue by xinthose** [kyle-github/libplctag#95]
Hello.  I am wondering what the maximum size of `elem_count` can be for an INT array in a MicroLogix 1400 for one tag to be written.  I know that you can give N type a maximum element size of 256 in RSLogix 500, but can a tag write that much?  

I am version 2.0+.

**Comment by kyle-github** [comment]
IIRC it is 110 2-byte words (INT).  About 220 bytes of payload.

I have had to split the PCCC code up, so now I am not sure if I can make
large array support transparent across all the PCCC PLC types.  It is on
the list of things to do.

Best,
Kyle

**Comment by xinthose** [comment]
OK.  I will keep this in mind as I develop my software.  Thank you Kyle.
~ Adam
