### ISSUE TITLE
Failed to read SubProgram variable tag

### ISSUE THREAD

**Issue by shouye0928** [kyle-github/libplctag#96]
I failed to read SubProgram variable tag,  SubProgram name is S030, variable name is z_TestDint[22],  and use S030:z_TestDint[22] as tag name, but failed to call plc_tag_create API function. Is this tag name correct?

**Comment by shouye0928** [comment]
How to read or write subprogram variable?

**Comment by kyle-github** [comment]
See issue #29.

You were very close.   You use it like this:

PROGRAM:S030.z_TestDint[22]

You need the word "PROGRAM" first, then a colon, ":", then the program name, "S030", then a dot, ".", then the tag name.

Please try that.

**Comment by kyle-github** [comment]
Also note that you need to allow reads in the permissions!

**Comment by shouye0928** [comment]
Kyle, thanks for the quick response, I will try it and post the results.

**Comment by shouye0928** [comment]
Use PROGRAM:S030.z_TestDint[22], it works well, thanks.

**Comment by kyle-github** [comment]
Closing if there are no other comments.
